import { LanguageCode } from "@app/shared-types/enums";

export const LanguageDisplayName: Record<LanguageCode, string> = {
    [LanguageCode.AFRIKAANS]: "Afrikaans",
    [LanguageCode.ALBANIAN]: "Albanian",
    [LanguageCode.AMHARIC]: "Amharic",
    [LanguageCode.ARABIC]: "Arabic",
    [LanguageCode.ARMENIAN]: "Armenian",
    [LanguageCode.AZERBAIJANI]: "Azerbaijani",
    [LanguageCode.BENGALI]: "Bengali",
    [LanguageCode.BOSNIAN]: "Bosnian",
    [LanguageCode.BULGARIAN]: "Bulgarian",
    [LanguageCode.CATALAN]: "Catalan",
    [LanguageCode.CHINESE_SIMPLIFIED]: "Chinese (Simplified)",
    [LanguageCode.CHINESE_TRADITIONAL]: "Chinese (Traditional)",
    [LanguageCode.CROATIAN]: "Croatian",
    [LanguageCode.CZECH]: "Czech",
    [LanguageCode.DANISH]: "Danish",
    [LanguageCode.DARI]: "Dari",
    [LanguageCode.DUTCH]: "Dutch",
    [LanguageCode.ENGLISH]: "English",
    [LanguageCode.ESTONIAN]: "Estonian",
    [LanguageCode.FARSI_PERSIAN]: "Farsi (Persian)",
    [LanguageCode.FILIPINO_TAGALOG]: "Filipino, Tagalog",
    [LanguageCode.FINNISH]: "Finnish",
    [LanguageCode.FRENCH]: "French",
    [LanguageCode.FRENCH_CANADA]: "French (Canada)",
    [LanguageCode.GEORGIAN]: "Georgian",
    [LanguageCode.GERMAN]: "German",
    [LanguageCode.GREEK]: "Greek",
    [LanguageCode.GUJARATI]: "Gujarati",
    [LanguageCode.HAITIAN_CREOLE]: "Haitian Creole",
    [LanguageCode.HAUSA]: "Hausa",
    [LanguageCode.HEBREW]: "Hebrew",
    [LanguageCode.HINDI]: "Hindi",
    [LanguageCode.HUNGARIAN]: "Hungarian",
    [LanguageCode.ICELANDIC]: "Icelandic",
    [LanguageCode.INDONESIAN]: "Indonesian",
    [LanguageCode.IRISH]: "Irish",
    [LanguageCode.ITALIAN]: "Italian",
    [LanguageCode.JAPANESE]: "Japanese",
    [LanguageCode.KANNADA]: "Kannada",
    [LanguageCode.KAZAKH]: "Kazakh",
    [LanguageCode.KOREAN]: "Korean",
    [LanguageCode.LATVIAN]: "Latvian",
    [LanguageCode.LITHUANIAN]: "Lithuanian",
    [LanguageCode.MACEDONIAN]: "Macedonian",
    [LanguageCode.MALAY]: "Malay",
    [LanguageCode.MALAYALAM]: "Malayalam",
    [LanguageCode.MALTESE]: "Maltese",
    [LanguageCode.MARATHI]: "Marathi",
    [LanguageCode.MONGOLIAN]: "Mongolian",
    [LanguageCode.NORWEGIAN_BOKMAL]: "Norwegian (Bokmål)",
    [LanguageCode.PASHTO]: "Pashto",
    [LanguageCode.POLISH]: "Polish",
    [LanguageCode.PORTUGUESE_BRAZIL]: "Portuguese (Brazil)",
    [LanguageCode.PORTUGUESE_PORTUGAL]: "Portuguese (Portugal)",
    [LanguageCode.PUNJABI]: "Punjabi",
    [LanguageCode.ROMANIAN]: "Romanian",
    [LanguageCode.RUSSIAN]: "Russian",
    [LanguageCode.SERBIAN]: "Serbian",
    [LanguageCode.SINHALA]: "Sinhala",
    [LanguageCode.SLOVAK]: "Slovak",
    [LanguageCode.SLOVENIAN]: "Slovenian",
    [LanguageCode.SOMALI]: "Somali",
    [LanguageCode.SPANISH]: "Spanish",
    [LanguageCode.SPANISH_MEXICO]: "Spanish (Mexico)",
    [LanguageCode.SWAHILI]: "Swahili",
    [LanguageCode.SWEDISH]: "Swedish",
    [LanguageCode.TAMIL]: "Tamil",
    [LanguageCode.TELUGU]: "Telugu",
    [LanguageCode.THAI]: "Thai",
    [LanguageCode.TURKISH]: "Turkish",
    [LanguageCode.UKRAINIAN]: "Ukrainian",
    [LanguageCode.URDU]: "Urdu",
    [LanguageCode.UZBEK]: "Uzbek",
    [LanguageCode.VIETNAMESE]: "Vietnamese",
    [LanguageCode.WELSH]: "Welsh",
};

export const LanguageFlag: Record<LanguageCode, string> = {
    [LanguageCode.AFRIKAANS]: "🇿🇦",
    [LanguageCode.ALBANIAN]: "🇦🇱",
    [LanguageCode.AMHARIC]: "🇪🇹",
    [LanguageCode.ARABIC]: "🇸🇦",
    [LanguageCode.ARMENIAN]: "🇦🇲",
    [LanguageCode.AZERBAIJANI]: "🇦🇿",
    [LanguageCode.BENGALI]: "🇧🇩",
    [LanguageCode.BOSNIAN]: "🇧🇦",
    [LanguageCode.BULGARIAN]: "🇧🇬",
    [LanguageCode.CATALAN]: "🇦🇩",
    [LanguageCode.CHINESE_SIMPLIFIED]: "🇨🇳",
    [LanguageCode.CHINESE_TRADITIONAL]: "🇹🇼",
    [LanguageCode.CROATIAN]: "🇭🇷",
    [LanguageCode.CZECH]: "🇨🇿",
    [LanguageCode.DANISH]: "🇩🇰",
    [LanguageCode.DARI]: "🇦🇫",
    [LanguageCode.DUTCH]: "🇳🇱",
    [LanguageCode.ENGLISH]: "🇬🇧",
    [LanguageCode.ESTONIAN]: "🇪🇪",
    [LanguageCode.FARSI_PERSIAN]: "🇮🇷",
    [LanguageCode.FILIPINO_TAGALOG]: "🇵🇭",
    [LanguageCode.FINNISH]: "🇫🇮",
    [LanguageCode.FRENCH]: "🇫🇷",
    [LanguageCode.FRENCH_CANADA]: "🇨🇦",
    [LanguageCode.GEORGIAN]: "🇬🇪",
    [LanguageCode.GERMAN]: "🇩🇪",
    [LanguageCode.GREEK]: "🇬🇷",
    [LanguageCode.GUJARATI]: "🇮🇳",
    [LanguageCode.HAITIAN_CREOLE]: "🇭🇹",
    [LanguageCode.HAUSA]: "🇳🇬",
    [LanguageCode.HEBREW]: "🇮🇱",
    [LanguageCode.HINDI]: "🇮🇳",
    [LanguageCode.HUNGARIAN]: "🇭🇺",
    [LanguageCode.ICELANDIC]: "🇮🇸",
    [LanguageCode.INDONESIAN]: "🇮🇩",
    [LanguageCode.IRISH]: "🇮🇪",
    [LanguageCode.ITALIAN]: "🇮🇹",
    [LanguageCode.JAPANESE]: "🇯🇵",
    [LanguageCode.KANNADA]: "🇮🇳",
    [LanguageCode.KAZAKH]: "🇰🇿",
    [LanguageCode.KOREAN]: "🇰🇷",
    [LanguageCode.LATVIAN]: "🇱🇻",
    [LanguageCode.LITHUANIAN]: "🇱🇹",
    [LanguageCode.MACEDONIAN]: "🇲🇰",
    [LanguageCode.MALAY]: "🇲🇾",
    [LanguageCode.MALAYALAM]: "🇮🇳",
    [LanguageCode.MALTESE]: "🇲🇹",
    [LanguageCode.MARATHI]: "🇮🇳",
    [LanguageCode.MONGOLIAN]: "🇲🇳",
    [LanguageCode.NORWEGIAN_BOKMAL]: "🇳🇴",
    [LanguageCode.PASHTO]: "🇦🇫",
    [LanguageCode.POLISH]: "🇵🇱",
    [LanguageCode.PORTUGUESE_BRAZIL]: "🇧🇷",
    [LanguageCode.PORTUGUESE_PORTUGAL]: "🇵🇹",
    [LanguageCode.PUNJABI]: "🇮🇳",
    [LanguageCode.ROMANIAN]: "🇷🇴",
    [LanguageCode.RUSSIAN]: "🇷🇺",
    [LanguageCode.SERBIAN]: "🇷🇸",
    [LanguageCode.SINHALA]: "🇱🇰",
    [LanguageCode.SLOVAK]: "🇸🇰",
    [LanguageCode.SLOVENIAN]: "🇸🇮",
    [LanguageCode.SOMALI]: "🇸🇴",
    [LanguageCode.SPANISH]: "🇪🇸",
    [LanguageCode.SPANISH_MEXICO]: "🇲🇽",
    [LanguageCode.SWAHILI]: "🇰🇪",
    [LanguageCode.SWEDISH]: "🇸🇪",
    [LanguageCode.TAMIL]: "🇮🇳",
    [LanguageCode.TELUGU]: "🇮🇳",
    [LanguageCode.THAI]: "🇹🇭",
    [LanguageCode.TURKISH]: "🇹🇷",
    [LanguageCode.UKRAINIAN]: "🇺🇦",
    [LanguageCode.URDU]: "🇵🇰",
    [LanguageCode.UZBEK]: "🇺🇿",
    [LanguageCode.VIETNAMESE]: "🇻🇳",
    [LanguageCode.WELSH]: "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
};