// Amazon Translate supported languages: https://docs.aws.amazon.com/translate/latest/dg/what-is-languages.html
export enum LanguageCode {
    AFRIKAANS = "af",
    ALBANIAN = "sq",
    AMHARIC = "am",
    ARABIC = "ar",
    ARMENIAN = "hy",
    AZERBAIJANI = "az",
    BENGALI = "bn",
    BOSNIAN = "bs",
    BULGARIAN = "bg",
    CATALAN = "ca",
    CHINESE_SIMPLIFIED = "zh",
    CHINESE_TRADITIONAL = "zh-TW",
    CROATIAN = "hr",
    CZECH = "cs",
    DANISH = "da",
    DARI = "fa-AF",
    DUTCH = "nl",
    ENGLISH = "en",
    ESTONIAN = "et",
    FARSI_PERSIAN = "fa",
    FILIPINO_TAGALOG = "tl",
    FINNISH = "fi",
    FRENCH = "fr",
    FRENCH_CANADA = "fr-CA",
    GEORGIAN = "ka",
    GERMAN = "de",
    GREEK = "el",
    GUJARATI = "gu",
    HAITIAN_CREOLE = "ht",
    HAUSA = "ha",
    HEBREW = "he",
    HINDI = "hi",
    HUNGARIAN = "hu",
    ICELANDIC = "is",
    INDONESIAN = "id",
    IRISH = "ga",
    ITALIAN = "it",
    JAPANESE = "ja",
    KANNADA = "kn",
    KAZAKH = "kk",
    KOREAN = "ko",
    LATVIAN = "lv",
    LITHUANIAN = "lt",
    MACEDONIAN = "mk",
    MALAY = "ms",
    MALAYALAM = "ml",
    MALTESE = "mt",
    MARATHI = "mr",
    MONGOLIAN = "mn",
    NORWEGIAN_BOKMAL = "no",
    PASHTO = "ps",
    POLISH = "pl",
    PORTUGUESE_BRAZIL = "pt",
    PORTUGUESE_PORTUGAL = "pt-PT",
    PUNJABI = "pa",
    ROMANIAN = "ro",
    RUSSIAN = "ru",
    SERBIAN = "sr",
    SINHALA = "si",
    SLOVAK = "sk",
    SLOVENIAN = "sl",
    SOMALI = "so",
    SPANISH = "es",
    SPANISH_MEXICO = "es-MX",
    SWAHILI = "sw",
    SWEDISH = "sv",
    TAMIL = "ta",
    TELUGU = "te",
    THAI = "th",
    TURKISH = "tr",
    UKRAINIAN = "uk",
    URDU = "ur",
    UZBEK = "uz",
    VIETNAMESE = "vi",
    WELSH = "cy",
};

export const LanguageDisplayName: Record<LanguageCode, string> = {
    [LanguageCode.AFRIKAANS]: "Afrikaans",
    [LanguageCode.ALBANIAN]: "Albanian",
    [LanguageCode.AMHARIC]: "Amharic",
    [LanguageCode.ARABIC]: "Arabic",
    [LanguageCode.ARMENIAN]: "Armenian",
    [LanguageCode.AZERBAIJANI]: "Azerbaijani",
    [LanguageCode.BENGALI]: "Bengali",
    [LanguageCode.BOSNIAN]: "Bosnian",
    [LanguageCode.BULGARIAN]: "Bulgarian",
    [LanguageCode.CATALAN]: "Catalan",
    [LanguageCode.CHINESE_SIMPLIFIED]: "Chinese (Simplified)",
    [LanguageCode.CHINESE_TRADITIONAL]: "Chinese (Traditional)",
    [LanguageCode.CROATIAN]: "Croatian",
    [LanguageCode.CZECH]: "Czech",
    [LanguageCode.DANISH]: "Danish",
    [LanguageCode.DARI]: "Dari",
    [LanguageCode.DUTCH]: "Dutch",
    [LanguageCode.ENGLISH]: "English",
    [LanguageCode.ESTONIAN]: "Estonian",
    [LanguageCode.FARSI_PERSIAN]: "Farsi (Persian)",
    [LanguageCode.FILIPINO_TAGALOG]: "Filipino, Tagalog",
    [LanguageCode.FINNISH]: "Finnish",
    [LanguageCode.FRENCH]: "French",
    [LanguageCode.FRENCH_CANADA]: "French (Canada)",
    [LanguageCode.GEORGIAN]: "Georgian",
    [LanguageCode.GERMAN]: "German",
    [LanguageCode.GREEK]: "Greek",
    [LanguageCode.GUJARATI]: "Gujarati",
    [LanguageCode.HAITIAN_CREOLE]: "Haitian Creole",
    [LanguageCode.HAUSA]: "Hausa",
    [LanguageCode.HEBREW]: "Hebrew",
    [LanguageCode.HINDI]: "Hindi",
    [LanguageCode.HUNGARIAN]: "Hungarian",
    [LanguageCode.ICELANDIC]: "Icelandic",
    [LanguageCode.INDONESIAN]: "Indonesian",
    [LanguageCode.IRISH]: "Irish",
    [LanguageCode.ITALIAN]: "Italian",
    [LanguageCode.JAPANESE]: "Japanese",
    [LanguageCode.KANNADA]: "Kannada",
    [LanguageCode.KAZAKH]: "Kazakh",
    [LanguageCode.KOREAN]: "Korean",
    [LanguageCode.LATVIAN]: "Latvian",
    [LanguageCode.LITHUANIAN]: "Lithuanian",
    [LanguageCode.MACEDONIAN]: "Macedonian",
    [LanguageCode.MALAY]: "Malay",
    [LanguageCode.MALAYALAM]: "Malayalam",
    [LanguageCode.MALTESE]: "Maltese",
    [LanguageCode.MARATHI]: "Marathi",
    [LanguageCode.MONGOLIAN]: "Mongolian",
    [LanguageCode.NORWEGIAN_BOKMAL]: "Norwegian (Bokmål)",
    [LanguageCode.PASHTO]: "Pashto",
    [LanguageCode.POLISH]: "Polish",
    [LanguageCode.PORTUGUESE_BRAZIL]: "Portuguese (Brazil)",
    [LanguageCode.PORTUGUESE_PORTUGAL]: "Portuguese (Portugal)",
    [LanguageCode.PUNJABI]: "Punjabi",
    [LanguageCode.ROMANIAN]: "Romanian",
    [LanguageCode.RUSSIAN]: "Russian",
    [LanguageCode.SERBIAN]: "Serbian",
    [LanguageCode.SINHALA]: "Sinhala",
    [LanguageCode.SLOVAK]: "Slovak",
    [LanguageCode.SLOVENIAN]: "Slovenian",
    [LanguageCode.SOMALI]: "Somali",
    [LanguageCode.SPANISH]: "Spanish",
    [LanguageCode.SPANISH_MEXICO]: "Spanish (Mexico)",
    [LanguageCode.SWAHILI]: "Swahili",
    [LanguageCode.SWEDISH]: "Swedish",
    [LanguageCode.TAMIL]: "Tamil",
    [LanguageCode.TELUGU]: "Telugu",
    [LanguageCode.THAI]: "Thai",
    [LanguageCode.TURKISH]: "Turkish",
    [LanguageCode.UKRAINIAN]: "Ukrainian",
    [LanguageCode.URDU]: "Urdu",
    [LanguageCode.UZBEK]: "Uzbek",
    [LanguageCode.VIETNAMESE]: "Vietnamese",
    [LanguageCode.WELSH]: "Welsh",
};